INSERT INTO DISCUSSIONTOPIC("id","description","long_description") VALUES('101','Account details - change', 'Change in the account details');
INSERT INTO DISCUSSIONTOPIC("id","description","long_description") VALUES('102','Account details - confirmed', 'Confirmation of the account details.');
INSERT INTO DISCUSSIONTOPIC("id","description","long_description") VALUES('103','Advisor', 'Introduce an advisor.');
INSERT INTO DISCUSSIONTOPIC("id","description","long_description") VALUES('104','ATO/Lost Super', 'Locating lost super.');
INSERT INTO DISCUSSIONTOPIC("id","description","long_description") VALUES('105','Balances', 'Balance inquiry.');
INSERT INTO DISCUSSIONTOPIC("id","description","long_description") VALUES('106','Beneficiaries', 'Update beneficiaries.');
INSERT INTO DISCUSSIONTOPIC("id","description","long_description") VALUES('107','Beneficiary nomination updated', 'Update beneficiary nominations');
INSERT INTO DISCUSSIONTOPIC("id","description","long_description") VALUES('108','Campaign 1', 'Placeholder for the first campaign');
INSERT INTO DISCUSSIONTOPIC("id","description","long_description") VALUES('109','Campaign 2', 'Placeholder for the second campaign');
INSERT INTO DISCUSSIONTOPIC("id","description","long_description") VALUES('110','Campaign 3', 'Placeholder for the third campaign');